package com.lulu.todayinhistory.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.lulu.todayinhistory.bean.localdata.TCollectMsg;
import com.lulu.todayinhistory.bean.localdata.TNotes;

import com.lulu.todayinhistory.dao.TCollectMsgDao;
import com.lulu.todayinhistory.dao.TNotesDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig tCollectMsgDaoConfig;
    private final DaoConfig tNotesDaoConfig;

    private final TCollectMsgDao tCollectMsgDao;
    private final TNotesDao tNotesDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        tCollectMsgDaoConfig = daoConfigMap.get(TCollectMsgDao.class).clone();
        tCollectMsgDaoConfig.initIdentityScope(type);

        tNotesDaoConfig = daoConfigMap.get(TNotesDao.class).clone();
        tNotesDaoConfig.initIdentityScope(type);

        tCollectMsgDao = new TCollectMsgDao(tCollectMsgDaoConfig, this);
        tNotesDao = new TNotesDao(tNotesDaoConfig, this);

        registerDao(TCollectMsg.class, tCollectMsgDao);
        registerDao(TNotes.class, tNotesDao);
    }
    
    public void clear() {
        tCollectMsgDaoConfig.clearIdentityScope();
        tNotesDaoConfig.clearIdentityScope();
    }

    public TCollectMsgDao getTCollectMsgDao() {
        return tCollectMsgDao;
    }

    public TNotesDao getTNotesDao() {
        return tNotesDao;
    }

}
